### ISSUE TITLE
Windows Issues

### ISSUE THREAD

**Issue by raholland79** [remix-run/starter-express#1]
EDIT: `node version 14.15.0`

Scripts set NODE_ENV the unix way.  Windows would be `set NODE_ENV=developement`.  I THINK separating the env variable and concurrently bit with `;` should work, but is failing for me.

To test I removed the NODE_ENV part and get the following when hitting localhost:3000

`Cannot find module ./App.tsx`

![image](https://user-images.githubusercontent.com/22954/97459483-d393a200-1909-11eb-9266-bac1be21cd47.png)

**Comment by ryanflorence** [comment]
I need to brush up on windows dev :|

Can you try implementing cross-env? https://www.npmjs.com/package/cross-env

**Comment by kevinbailey25** [comment]
Installed `cross-env` and updated my `start` script to 

```cross-env NODE_ENV=development concurrently \"remix run\" \"tsc -b -w\" \"nodemon --ignore app server.js\"```

Seems to work, but I get the same error that is posted above when I try to navigate to `http://localhost:3000/`

![image](https://user-images.githubusercontent.com/36492257/97497955-f9806d00-1930-11eb-9aab-4318734d6d37.png)

**Comment by raholland79** [comment]
Yes, cross-env will fix the environment issue but the other error remains.

**Comment by ryanflorence** [comment]
Can you help me get my windows machine working? I can't run any cli tools from npm install. Can't do `remix` or `concurrently` or `cross-env` etc.

I'm using powershell and installed node with chocolatey.

**Comment by ryanflorence** [comment]
We found the problem, fix will be out in 0.6.2
