### ISSUE TITLE
Out-dated filename in root.tsx

### ISSUE THREAD

**Issue by codeclown** [remix-run/starter-express#17]
In `root.tsx`, should probably read `root.tsx` instead of `App.tsx`?

https://github.com/remix-run/starter-express/blob/fde4506533a1619fa1da3980a0cf06951ed6b95a/app/root.tsx#L50

**Comment by mjackson** [comment]
Fixed in ba1cc3acc38b8a810a3c6b6c17045fdf9d481c3e
