### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by sbrichardson** [remix-run/starter-express#2]
Received this error with initial repo installation. (node v10 & v12)

```bash
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@remix-run%2fexpress - Not found
npm ERR! 404
npm ERR! 404  '@remix-run/express@0.6.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'starter-express'
```

**Comment by sbrichardson** [comment]
```bash
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@remix-run%2fexpress - Not found
npm ERR! 404
npm ERR! 404  '@remix-run/express@0.6.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'starter-express'
```

**Comment by Asjas** [comment]
@sbrichardson You did create a `.npmrc` in the local project folder that contains your token as well as the Remix NPM Registry? Also, you can use Node.js 12 as that is the [supported version](https://github.com/remix-run/starter-express/blob/master/package.json#L28).

```js
//npm.remix.run/:_authToken=<your token>
@remix-run:registry=https://npm.remix.run
```

https://remix.run/dashboard/docs/tutorial/installation

**Comment by mjackson** [comment]
I think you may just need to setup your `.npmrc` as described [here](https://github.com/remix-run/starter-express#development).

**Comment by mjackson** [comment]
Gonna close this because I assume it's due to not setting up npmrc correctly.
